export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const COIN_DATA_REQUEST = 'COIN_DATA_REQUEST';
export const COIN_DATA_SUCCESS = 'COIN_DATA_SUCCESS';
export const COIN_DATA_FAILED = 'COIN_DATA_FAILED';
export const SET_COIN_CLICKED = 'SET_COIN_CLICKED';

export const SAVED_DATA_LOADING = 'SAVED_DATA_LOADING';
export const GET_ALL_SAVED_DATA = 'GET_ALL_SAVED_DATA';
export const GET_SINGLE_SAVE = 'GET_SINGLE_SAVE';
export const ADD_SAVE_DATA = 'ADD_SAVE_DATA';
export const DELETE_SAVE_DATA = 'DELETE_SAVE_DATA';
